### ISSUE TITLE
Configuring axe rules

### ISSUE THREAD

**Issue by nicklemmon** [avanslaars/cypress-axe#1]
Hello,

Love the product! This is a great idea and way to manage a11y development, creating a much tighter feedback loop.

I wanted to request support for configuring axe rule enforcement - some rules are inappropriately enforced in certain scenarios, leading to false positives. Ideally in `cypress/support/index.js` a config file could be passed in, leveraging `axe.configure()`.

This may already be possible! If so, just some simple docs with an example would suffice.

**Comment by samcus** [comment]
@nicklemmon please look at my pull request. Once it is approved you will be able to do this. (or you can use my fork until then).

**Comment by nicklemmon** [comment]
Thanks for doing that, @samcus - hopefully the maintainer will approve. I'll take a look at your fork.

**Comment by avanslaars** [comment]
This was just merged in an is available in the latest version. Thanks @samcus
