### ISSUE TITLE
ReferenceError: exports is not defined when calling injectAxe() through typescript

### ISSUE THREAD

**Issue by dagda1** [avanslaars/cypress-axe#11]
I have this in my `support/index.ts`

my tsconfig.json looks like this:

```
{
  "compilerOptions": {
    "lib": [
      "dom",
      "es2015",
      "es5",
      "es6",
      "es2015"
    ],
    "target": "es5",
    "module": "commonjs",
    "noImplicitAny": false,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
  },
  "files": [
    "./support/index.d.ts"
  ]
}

```

I have this test:
```
describe("TypeScript", () => {
  it("checks shape of an object", () => {
    cy.visit('http://localhost:6001')
    cy.injectAxe();
  });
})
```

It fails with 

> ReferenceError: exports is not defined
>       at axeFunction (eval at cy.window.then.window (http://localhost:6001/__cypress/tests?p=cypress/support/index.ts-538:111:12), <anonymous>:16:14)
>       at eval (eval at cy.window.then.window (http://localhost:6001/__cypress/tests?p=cypress/support/index.ts-538:111:12), <anonymous>:15287:3)
>       at eval (<anonymous>)

Why would this be?

**Comment by Annie-Huang** [comment]
What is the fix for this problem? I got the same one....

**Comment by rlaucik** [comment]
Also curious about solution. @dagda1 did you find a way how to avoid this?

**Comment by avanslaars** [comment]
@rlaucik @Annie-Huang The latest release of cypress-axe (`0.8.1`) should take care of this issue.

**Comment by hugotox** [comment]
Having this issue with `cypress-axe@0.9.1` and `cypress-axe@0.8.2`. As @avanslaars said, `cypress-axe@0.8.1` is the only one that works

**Comment by pstenstrm** [comment]
I have the same issue with `cypress-axe@0.9.1`, downgrading to `cypress-axe@0.8.1` as @hugotox mentioned works.

I run `cypress@5.3.0` and  `axe-core@4.0.2`.

**Comment by joshje** [comment]
Also getting this issue with `cypress-axe@0.9.1` `axe-core@4.0.2` and `cypress@5.4.0`. Is there a fix on the way?

**Comment by ee92** [comment]
same issue with 
```
"devDependencies": {
        "cypress": "^5.5.0",
        "cypress-axe": "^0.9.1",
        "axe-core": "^4.0.2"
}
```
