### ISSUE TITLE
Fail test only on a particular impact level

### ISSUE THREAD

**Issue by akapitoha** [avanslaars/cypress-axe#19]
Hi,

is it possible to configure cypress-axe, so it fails tests only if there, for example, `critical` violations?

**Comment by avanslaars** [comment]
I have a working prototype for this, just trying to decide on the final API. I'll try to get it in this week.

**Comment by avanslaars** [comment]
I've just published `0.8.0` which now allows for an `includedImpacts` key to be added to the `options` argument of `cy.checkA11y`. Pass it an array of strings with the impact level(s) you want to assert against.

This test will only fail for critical issues:

```js
cy.checkA11y(null, {
  includedImpacts: ['critical']
})
```

Check out the updated docs here: https://github.com/avanslaars/cypress-axe#options-optional
