### ISSUE TITLE
Specify selector on cy.checkA11y()

### ISSUE THREAD

**Issue by dalemanthei** [avanslaars/cypress-axe#2]
I'm working on a component library so my focus in a11y testing of the components rather than the test harness they're loaded in. In protractor we can do something like:

`browser.runAxeTest('Breadcrumbs', 'lib-breadcrumbs');`

Looking at some of the discussion [here](https://github.com/dequelabs/axe-core/issues/130), it seems like axe-core allows specificity.

It looks like it might be a simple passing of a selector as a parameter to the `cy.checkA11y();` to propagate to axe API.

Does this seem like it would be a good approach? Or would using axe directly be preferable?

**Comment by samcus** [comment]
@dalemanthei please look at my pull request. Once it is approved you will be able to do this. (or you can use my fork until then).

**Comment by avanslaars** [comment]
The PR from @samcus has been merged and published. This should be all good now.
