### ISSUE TITLE
Disable a rule

### ISSUE THREAD

**Issue by hannahhaken** [avanslaars/cypress-axe#23]
Hi, is it possible to disable a rule via ID when running cy.checkA11y() on a page? 

We're already aware of the color-contrast issue we have on our pages and until our site rebrand this will remain an a11y issue.

I've read the provided documentation and tried a few different variations (passing just an array through, removing [] brackets etc) of the below but the rule still appears to be checked:

```   
        cy.injectAxe()
        cy.configureAxe({
            rules: [{ 'aria-hidden-focus': { enabled: false } }]
        })
        cy.checkA11y()
```

![image](https://user-images.githubusercontent.com/17891217/72609148-2d4b5280-391c-11ea-90aa-4de84a626a0b.png)

**Comment by hannahhaken** [comment]
Looks like it might have been a webpack issue. I installed this and it now works https://www.npmjs.com/package/better-cypress-axe

**Comment by AElmoznino** [comment]
@hannahhaken did you figure out any way to disable a rule? I have a similar issue with skip-links (but don't want to switch to the other package)

**Comment by hannahhaken** [comment]
@AElmoznino I ended up adding better-cypress-axe which seemed to fix my webpack issues and allowed me to use this code to ignore rules.

```        cy.injectAxe()
        cy.configureAxe({
            rules: [
                {
                    id: 'aria-hidden-focus',
                    enabled: false
                },
                {
                    id: 'color-contrast',
                    enabled: false
                },
                {
                    id: 'aria-allowed-role',
                    enabled: false
                }
            ]
        })
        cy.checkA11y()
```

**Comment by hugotox** [comment]
no need to install anything else, just use the axe API https://www.deque.com/axe/axe-for-web/documentation/api-documentation/#options-parameter

E.g

```
    cy.checkA11y('body', {
      rules: {
        'color-contrast': { enabled: false },
      },
    })
```

**Comment by redbmk** [comment]
Took me a minute but looks like if you want the equivalent of `cy.checkA11y()` (which can give different results than using the `'body'` selector), you can pass in `undefined`.

    cy.checkA11y(undefined, {
      rules: {
        'color-contrast': { enabled: false },
      },
    })
