### ISSUE TITLE
Disabaling axe rules

### ISSUE THREAD

**Issue by wagg-matt** [avanslaars/cypress-axe#3]
Hi, 

Is there a way to disable certain axe rules? We're looking to run it through CI and gradually update accessibility errors as we go then enable the rules once they're updated.

Is there a way to do this?

Thanks

**Comment by samcus** [comment]
@wagg-matt please look at my pull request. Once it is approved you will be able to do this. (or you can use my fork until then).

**Comment by avanslaars** [comment]
The PR @samcus submitted has been merged and the latest version has been released.
