### ISSUE TITLE
How run just a single rule?

### ISSUE THREAD

**Issue by bahmutov** [avanslaars/cypress-axe#9]
Still after reading axe-core docs cannot for the life of me figure out how to run a single rule, for example how to run just "color-contrast" rule against text on the page...

**Comment by marcysutton** [comment]
@bahmutov you can use the `runOnly` API: https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter

**Comment by bahmutov** [comment]
Perfect, it works, wrote blog post https://glebbahmutov.com/blog/fix-low-contrast-with-cypress/
